### ISSUE TITLE
Allow final grade calculation based on points

### ISSUE THREAD

**Issue by stgm** [stgm/course-site#436]
Currently it's hard/impossible to calculate final grades if components need to be added instead of averaged.

Would like to be able to specify a **points** strategy:

```
calculation:
    type: points
    eindcijfer:
        tentamen: 5
        punten: 4
    eindcijfer_herkansing:
        hertentamen: 5
        punten: 4
```

Grade should then be `added / total_possible * 9 + 1`.
